config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' 	=> 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # using simplified regex, duplicated dots (.) are allowed
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	# Returns the hash digest of the given string
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome to Culture Companion!"
			redirect_to @user
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# returns the full title on a per-page basis
	def full_title(page_title = '')
		base_title = "Culture Companion"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=200"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created 2016, by <a href="http://timpaisley.net/">Tim Paisley</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><a href="http://tepapa.timpaisley.net/">Proposal</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
	<nav>
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "Culture Companion", root_path, id: "logo" %>
			</div>

			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<% if logged_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li class="divider"></li>
							<li><%= link_to "Log out", logout_path, method: "delete" %></li>
						</ul>
					</li>
					<% else %>
					<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,400italic,700|Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<!--<%= debug(params) if Rails.env.development? %>-->
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>So what's all of this about, then?</h1>
<p class="lead">Glad you asked! Te Papa Culture Companion is a 'Web-based Companion App' for our Te Papa exhibits. In other words, it's a website that can accompany you on your smart phone, tablet, or laptop while you look around Te Papa, providing extra information, videos, audio snippets and additional material to complete your Te Papa experience. It can even make suggestions on what you might want to check out next!</p>

<h1>How does it work?</h1>
<p class="lead">Te Papa Culture Companion uses a range of different technologies to make it as easy as possible for you to get more information about each part of an exhibition. You'll find NFC tags, QR codes, and unique ID codes scattered around Te Papa which will take you to each different section of the web site.</p>

<!-- DIVE DEEPER -->
<h1>But why should you bother?</h1>
<p class="lead">Have you ever found a display in a museum that really gets you thinking? Something that interests you, something that you want to know more about? When we put together an exhibit, we selected some of the most important parts to show you, but there's so much more beneath the surface which we can't possibly fit! More stories, pictures, audio recordings and videos than you can sink your teeth into, and all in one easy-to-use online repository, ready at your fingertips for you to dive in.</p>

<center><div class="col-md-3">
	<h2 class="text-muted"><span class="glyphicon glyphicon-film" aria-hidden="true"></span> Videos</h2>
</div>

<div class="col-md-3">
	<h2 class="text-muted"><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span> Audio</h2>
</div>

<div class="col-md-3">
	<h2 class="text-muted"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span> Photos</h2>
</div>

<div class="col-md-3">
	<h2 class="text-muted"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Maps</h2>
</div></center>

<h2>&nbsp;</h2>
<h1>How can we make your experience more personal?</h1>
<p class="lead">When you decide to sign up for a Culture Companion account, one of the things that we recommend you do first is to take a short survey. The survey will ask you a few easy questions, such as how old you are and what you're interests are. This information will be used not only to help us make your experience better in the future, but also to curate your <i>Recommended</i> section - when you're ready to move onto something else, we can provide some handy suggestions on what we think you might like.</p>

<!-- EARN POINTS -->
<h1>How do you earn points?</h1>
<p class="lead">Every time you tag onto a display article using NFC, QR codes or its unique ID, we'll give you some points! Your points will be kept on your account, and you'll be able to track your progress through our exhibits on your <i>Profile</i> page. Tag all displays in an exhibit to get 100% completion, then prove you're an expert on the topic by trying our exhibit quizzes to earn even more points!</p>

<h1>What do the points do?</h1>
<p class="lead">We understand that kids can sometimes need a bit of persuation when it comes to learning, and with Culture Companion we award points for doing just that! Completing quizzes in each exhibit will unlock bonus digital content such as wallpapers and printable crafts. More points will score you small discounts in the gift store and for some exhibits, there may even be small goodie bags waiting in the gift shop for those who've done well.</p>

<div class="container">
	<h1>What are you waiting for?</h1>
	<p class="lead">That's all you need to know for now! If you like the sound of an easy-to-use online tour guide to expand and personalise your experience at Te Papa, sign up for a completely free account now <%= link_to "sign up for a completely free account now", signup_path %>!</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Culture Companion - Help</h1>
<p>In development</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>The Official Te Papa Companion</h1>
	<h2>Your all-in-one tour guide as you dive into culture, history and art!</h2>

	<%= link_to "Create an Account", signup_path, class: "btn btn-lg btn-success" %>
</div>

<!-- News Text -->
<div class="row">
	<div class="col-md-4">
		<h3>News Article 1</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget pretium dolor, in feugiat sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi faucibus accumsan dictum. Suspendisse potenti. Vivamus vel est eget lorem lobortis imperdiet at id lacus. Donec ullamcorper faucibus nibh ut posuere. Morbi ac eleifend metus. Integer et laoreet ligula. Ut fermentum cursus quam, eu convallis magna tincidunt vitae. Nunc posuere, augue ac maximus pharetra, sem erat iaculis dolor, sed pretium felis mauris auctor odio. Curabitur vitae semper nulla, at scelerisque dui.</p>
		<%= link_to "Read More »", '#', class: "btn btn-default" %>
	</div>

	<div class="col-md-4">
		<h3>News Article 2</h3>
		<p>Cras vulputate placerat varius. Etiam eleifend magna sit amet tellus sagittis imperdiet. Aenean eget congue eros. Integer non arcu vitae libero varius convallis sed nec nibh. Nulla eget ullamcorper ligula. Maecenas ac lobortis sapien. Praesent felis est, interdum nec nunc sit amet, ultrices condimentum enim. Proin tincidunt, lectus id dignissim iaculis, mauris nunc rhoncus quam, id auctor risus nunc et ex. Fusce in fermentum turpis.</p>
		<%= link_to "Read More »", '#', class: "btn btn-default" %>
	</div>

	<div class="col-md-4">
		<h3>News Article 3</h3>
		<p>Praesent vehicula sit amet turpis vitae semper. Sed commodo mollis neque sed sollicitudin. Suspendisse convallis a dui vel faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce efficitur cursus ornare. Integer porttitor nunc quis tempus ornare. Fusce pulvinar nulla nec nisi tempor, consectetur congue mi sagittis. Sed eu lectus et massa hendrerit pulvinar et eu dui. Mauris a venenatis enim, sit amet commodo lectus. Suspendisse vitae nisl mattis mauris tempor sagittis sed vitae nisl.</p>
		<%= link_to "Read More »", '#', class: "btn btn-default" %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row user-exhibits">
	<div class="col-md-3">
		<div class="user-details">
			<%= gravatar_for @user %>
			<h1><%= @user.name %></h1>
			<h2>500 Points</h2>
		</div>
	</div>

	<div class="col-md-9">
		<div class="exhibit-block">
			<h2>Exhibit 1</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget pretium dolor...</p>
		</div>

		<div class="exhibit-block">
			<h2>Exhibit 2</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget pretium dolor...</p>
		</div>

		<div class="exhibit-block">
			<h2>Exhibit 3</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget pretium dolor...</p>
		</div>

		<div class="exhibit-block">
			<h2>Exhibit 4</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget pretium dolor...</p>
		</div>

		<div class="exhibit-block">
			<h2>Exhibit 5</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget pretium dolor...</p>
		</div>
	</div>
</div>